<!DOCTYPE html>
<html>
<head>
  <title>Intro to R for the C# Developer</title>
  <meta charset="utf-8">
  <meta name="description" content="Intro to R for the C# Developer">
  <meta name="author" content="Elizabeth Groom">
  <meta name="generator" content="slidify" />
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta http-equiv="X-UA-Compatible" content="chrome=1">
  <link rel="stylesheet" href="libraries/frameworks/io2012/css/default.css" media="all" >
  <link rel="stylesheet" href="libraries/frameworks/io2012/css/phone.css" 
    media="only screen and (max-device-width: 480px)" >
  <link rel="stylesheet" href="libraries/frameworks/io2012/css/slidify.css" >
  <link rel="stylesheet" href="libraries/highlighters/highlight.js/css/tomorrow.css" />
  <base target="_blank"> <!-- This amazingness opens all links in a new tab. -->  
  
  <!-- Grab CDN jQuery, fall back to local if offline -->
  <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.7.min.js"></script>
  <script>window.jQuery || document.write('<script src="libraries/widgets/quiz/js/jquery.js"><\/script>')</script> 
  <script data-main="libraries/frameworks/io2012/js/slides" 
    src="libraries/frameworks/io2012/js/require-1.0.8.min.js">
  </script>
  
  

</head>
<body style="opacity: 0">
  <slides class="layout-widescreen">
    
    <!-- LOGO SLIDE -->
        <slide class="title-slide segue nobackground">
  <hgroup class="auto-fadein">
    <h1>Intro to R for the C# Developer</h1>
    <h2>(Use arrow keys to navigate)</h2>
    <p>Elizabeth Groom<br/>Software Engineer at Cartegraph\Data enthusiast</p>
  </hgroup>
  <article></article>  
</slide>
    

    <!-- SLIDES -->
    <slide class="" id="slide-1" style="background:;">
  <hgroup>
    <h2>About me</h2>
  </hgroup>
  <article data-timings="">
    <p>Elizabeth Groom
Software Engineer Cartegraph in Dubuque</p>

<p>email me: <a href="mailto:eagroom@yahoo.com">eagroom@yahoo.com</a><br>
find this presentation on github at: <a href="https://github.com/eagroom/IntroToRPresentation">https://github.com/eagroom/IntroToRPresentation</a>  </p>

<p><code>presentation built using slidfy in R</code> </p>

  </article>
  <!-- Presenter Notes -->
  <aside class="note" id="">
    <section>
      <p>11 years at Cartegraph<br>
java script (knockout) application with a c# backend<br>
I think data science is important and it will become more important  </p>

<p>no real qualifications for this presenation other than<br>
taking the coursera data science specialization  </p>

    </section>
  </aside>
</slide>

<slide class="" id="slide-2" style="background:;">
  <hgroup>
    <h2>Why this is important</h2>
  </hgroup>
  <article data-timings="">
    <p>Consider the case study presented by Keith Baggerly <a href="http://videolectures.net/cancerbioinformatics2010_baggerly_irrh/">The Anil Potti Story</a></p>

<p>Article: &quot;<a href="http://www.nature.com/nm/journal/v12/n11/abs/nm1491.html">Genomic signatures to guide the use of chemotherapeutics.</a>&quot;
  Auther: Potti et al (2006), 
  Magazine: Nature Medicine, 12:1294-1300</p>

<p>The idea is they developed a tool that can be used to predict weather a patient will respond to chemotherapies by knowing what drugs are most effective against which cells.  </p>

<p><b>Amazing!</b></p>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-3" style="background:;">
  <hgroup>
    <h2>Why Cont.</h2>
  </hgroup>
  <article data-timings="">
    <p>This was very exciting to the MD Anderson Cancer Center.  They asked Baggerly&#39;s group to evaluate this new tool.</p>

<p>What Baggerly found was poor data analysis as several steps along the way.  Easy things like miss labeling of data.  This caused patients to not get the drugs that it is predicted their cancer would respond best to!</p>

<p>&quot;Intuition in high through put biology is poor&quot; -Keith Baggerly </p>

<p>In other words... we need impartial engineers who care deeply about the process and the math the data is curated through so that doctors, geneticist, ect. can learn factual things from the data and draw acurate conclusions.</p>

  </article>
  <!-- Presenter Notes -->
  <aside class="note" id="">
    <section>
      <p>Their theory was sound<br>
the source data was good<br>
Humans are poor fortune tellers   </p>

<p>implement all the good process we as software engineers have discovered along the way:<br>
Pair programming, code reviews, unit tests, test driven development, open source software -&gt; open source   equations<br>
Off my soap box and on to the good stuff  </p>

    </section>
  </aside>
</slide>

<slide class="" id="slide-4" style="background:;">
  <hgroup>
    <h2>What is R</h2>
  </hgroup>
  <article data-timings="">
    <ul>
<li>R is an <b>interactive</b> system for statistical computation and graphics. It consists of a language <code>plus a run-time environment with graphics</code>, a debugger, and the ability to run programs stored in script files. It is open source.</li>
</ul>

<ul class = "build incremental">
<li><p>R is a dialect of the S language.</p></li>
<li><p>S is a language that was developed by John Chambers and others at Bell Labs. It was initiated in 1976 as an internal statistical analysis environment-originally implemented as Fortran libraries. (In 1988 the system was rewritten in C)</p></li>
<li><p>&quot;[W]e wanted users to be able to begin in an <b>interactive</b> environment, where they did not consciously think of themselves as programming. Then as their needs became clearer and their sophistication increased, they should be able to <b>slide gradually into programming</b>, when the language and system aspects would become more important.&quot; John Chambers</p></li>
</ul>

  </article>
  <!-- Presenter Notes -->
  <aside class="note" id="">
    <section>
      <p>Good for newbie programmers, but can be harder for others<br>
Not written as a programming language first, but an interactive environment first.<br>
this history give us context as we try to figure out how to use the system  </p>

    </section>
  </aside>
</slide>

<slide class="" id="slide-5" style="background:;">
  <hgroup>
    <h2>What is R Cont.</h2>
  </hgroup>
  <article data-timings="">
    <ul>
<li><p>In 1991 Ross Ihaka and Robert Gentleman created R</p></li>
<li><p>Runs on almost any standard computing platform/OS (even on the PlayStation 3)</p></li>
<li><p>Frequent releases (annual + bugfix releases); active development.</p></li>
</ul>

  </article>
  <!-- Presenter Notes -->
  <aside class="note" id="">
    <section>
      <p>Mathematics of New Zealand<br>
Mathematics not computer scientists<br>
Apple OS does have some functional difference with Windows  </p>

    </section>
  </aside>
</slide>

<slide class="" id="slide-6" style="background:;">
  <hgroup>
    <h2>The Tools</h2>
  </hgroup>
  <article data-timings="">
    <ul>
<li><p>R comes with an IDE.  Its not bad.</p></li>
<li><p>Recommend RStudio. It&#39;s <b><code>free</code></b> and includes a lot of great features, similar to a scaled down visual studio, like syntax highlighting, auto completion and integrated help.<br>
<a href="http://www.rstudio.com/">http://www.rstudio.com/</a></p></li>
</ul>

  </article>
  <!-- Presenter Notes -->
  <aside class="note" id="">
    <section>
      <p>Show R and Rstudio</p>

    </section>
  </aside>
</slide>

<slide class="" id="slide-7" style="background:;">
  <hgroup>
    <h2>Variable assignment</h2>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">x&lt;- 1
</code></pre>

<p>The assignment operator is an &quot;&lt;-&quot;.  You can read it as &quot;x gets 1&quot;</p>

<pre><code class="r">1 -&gt; x #is also valid
</code></pre>

  </article>
  <!-- Presenter Notes -->
  <aside class="note" id="">
    <section>
      <p>highlight influenced by mathematics  </p>

    </section>
  </aside>
</slide>

<slide class="" id="slide-8" style="background:;">
  <hgroup>
    <h2>Two more ways to assign variables</h2>
  </hgroup>
  <article data-timings="">
    <p>&quot;=&quot;.  Works in &quot;most&quot; contexts</p>

<pre><code class="r">x = 1
</code></pre>

<p>assign function</p>

<pre><code class="r">assign(&quot;x&quot;, 1)
</code></pre>

<p>This leads me to the first thing that I learned the hard way about R. <code>There are at least 3 ways to do any one thing in R and they each work in &quot;most&quot; contexts.</code></p>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-9" style="background:;">
  <hgroup>
    <h2>Auto print</h2>
  </hgroup>
  <article data-timings="">
    <p>To print out value of x:</p>

<pre><code class="r">x&lt;- 10
x
</code></pre>

<pre><code>## [1] 10
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-10" style="background:;">
  <hgroup>
    <h2>Vectors</h2>
  </hgroup>
  <article data-timings="">
    <p>Notice how X prints out : [1] 10</p>

<p>The simplest structure in R is the numeric vector. The number in brackets denotes the number of items in the vector.  </p>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-11" style="background:;">
  <hgroup>
    <h2>Vectors cont.</h2>
  </hgroup>
  <article data-timings="">
    <p>R has five basic classes of objects:</p>

<ul>
<li>character</li>
<li>numeric (real numbers)</li>
<li>integer</li>
<li>complex</li>
<li>logical (True/False)<br>
And...<br></li>
<li>Factors</li>
</ul>

<p>A vector can only contain objects of the same class</p>

  </article>
  <!-- Presenter Notes -->
  <aside class="note" id="">
    <section>
      <p>complex = imaginary numbers<br>
list objects = lists are collections of vectors where objects don&#39;t have to be the same type<br>
Factors are not first class citizens in R<br>
A &quot;factor&quot; is a vector whose elements can take on one of a specific set of values. For example, &quot;Sex&quot; will usually take on only the values &quot;M&quot; or &quot;F,&quot; whereas &quot;Name&quot; will generally have lots of possibilities. The set of values that the elements of a factor can take are called its levels.</p>

    </section>
  </aside>
</slide>

<slide class="" id="slide-12" style="background:;">
  <hgroup>
    <h2>Vectors</h2>
  </hgroup>
  <article data-timings="">
    <p>We can check the vector type with the function class</p>

<pre><code class="r">class(x)
</code></pre>

<pre><code>## [1] &quot;numeric&quot;
</code></pre>

<p>you might have expected 10 to be an integer but in R an integer is denoted with an <code>L</code></p>

<pre><code class="r">x&lt;-10L
 class(x)
</code></pre>

<pre><code>## [1] &quot;integer&quot;
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-13" style="background:;">
  <hgroup>
    <h2>Vector Math</h2>
  </hgroup>
  <article data-timings="">
    <p>The fact that Vectors are the simplest structure makes vector math intrinsic to the application.</p>

<pre><code class="r">x&lt;-sample(1:20, 5)
x
</code></pre>

<pre><code>## [1] 17  3  6 10 12
</code></pre>

<pre><code class="r">x - 4
</code></pre>

<pre><code>## [1] 13 -1  2  6  8
</code></pre>

  </article>
  <!-- Presenter Notes -->
  <aside class="note" id="">
    <section>
      <p>since in R we are generally always working with a set of data, it becomes truly awesome that vectors are the simplest object  </p>

<p>note on notation:<br>
1:20 give me the range between 1 and 20 and it gives me random 5 objects from that sample<br>
to get random numbers use: rnorm(n, mean = 0, sd = 1)<br>
  rnorm = set of random numbered from the normal distribution with a mean of 0 and standard deviation of 1  </p>

    </section>
  </aside>
</slide>

<slide class="" id="slide-14" style="background:;">
  <hgroup>
    <h2>Vector Math</h2>
  </hgroup>
  <article data-timings="">
    <p>The previous exmaple might seem contrived example, but consider if you want to normalize data in preparation for fitting a regression model</p>

<pre><code class="r">#center the data by subtracting the mean
xc&lt;-x-mean(x)

#scale the data by dividing by the standard deviation
xn&lt;-xc/sd(x)

xn
</code></pre>

<pre><code>## [1]  1.36709253 -1.21929874 -0.66507204  0.07389689  0.44338136
</code></pre>

  </article>
  <!-- Presenter Notes -->
  <aside class="note" id="">
    <section>
      <p>The process of centering then scaling the data is called &quot;normalizing&quot; the data<br>
normalized data has a mean of 0 and a standard deviation of 1  </p>

    </section>
  </aside>
</slide>

<slide class="" id="slide-15" style="background:;">
  <hgroup>
    <h2>Data frames - The most useful object</h2>
  </hgroup>
  <article data-timings="">
    <p>A data frame for all intents and purposes is a table.</p>

<ul>
<li>Each columns is a vector</li>
<li>Each column has the same length</li>
<li>Columns can have labels</li>
</ul>

<p>Let&#39;s Check out one of the sample datasets in R: mtCars</p>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-16" style="background:;">
  <hgroup>
    <h2>Data frames</h2>
  </hgroup>
  <article data-timings="">
    <p>Head and Tail function let you see the top, or bottom rows of data.  By default they show 6 rows.</p>

<pre><code class="r">head(mtcars)
</code></pre>

<pre><code>##                    mpg cyl disp  hp drat    wt  qsec vs am gear carb
## Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
## Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
## Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
## Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
## Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
## Valiant           18.1   6  225 105 2.76 3.460 20.22  1  0    3    1
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-17" style="background:;">
  <hgroup>
    <h2>Data frames</h2>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">tail(mtcars, 4)
</code></pre>

<pre><code>##                 mpg cyl disp  hp drat   wt qsec vs am gear carb
## Ford Pantera L 15.8   8  351 264 4.22 3.17 14.5  0  1    5    4
## Ferrari Dino   19.7   6  145 175 3.62 2.77 15.5  0  1    5    6
## Maserati Bora  15.0   8  301 335 3.54 3.57 14.6  0  1    5    8
## Volvo 142E     21.4   4  121 109 4.11 2.78 18.6  1  1    4    2
</code></pre>

  </article>
  <!-- Presenter Notes -->
  <aside class="note" id="">
    <section>
      <p>one way of setting the optional parameter, could also have done tail(mtcars, n=4)</p>

    </section>
  </aside>
</slide>

<slide class="" id="slide-18" style="background:;">
  <hgroup>
    <h2>Data frames</h2>
  </hgroup>
  <article data-timings="">
    <p>Data Frames have some helpful functions to help you get to know your data:</p>

<p>The str function: displays the structure of an object</p>

<pre><code class="r">str(mtcars)
</code></pre>

<pre><code>## &#39;data.frame&#39;:    32 obs. of  11 variables:
##  $ mpg : num  21 21 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 ...
##  $ cyl : num  6 6 4 6 8 6 8 4 4 6 ...
##  $ disp: num  160 160 108 258 360 ...
##  $ hp  : num  110 110 93 110 175 105 245 62 95 123 ...
##  $ drat: num  3.9 3.9 3.85 3.08 3.15 2.76 3.21 3.69 3.92 3.92 ...
##  $ wt  : num  2.62 2.88 2.32 3.21 3.44 ...
##  $ qsec: num  16.5 17 18.6 19.4 17 ...
##  $ vs  : num  0 0 1 1 0 1 0 1 1 1 ...
##  $ am  : num  1 1 1 0 0 0 0 0 0 0 ...
##  $ gear: num  4 4 4 3 3 3 3 4 4 4 ...
##  $ carb: num  4 4 1 1 2 1 4 2 2 4 ...
</code></pre>

  </article>
  <!-- Presenter Notes -->
  <aside class="note" id="">
    <section>
      <p>the meta data for the columns<br>
11 columns and 32 rows  </p>

    </section>
  </aside>
</slide>

<slide class="" id="slide-19" style="background:;">
  <hgroup>
    <h2>Data frames</h2>
  </hgroup>
  <article data-timings="">
    <p>The summary function: displays some summary information about the object</p>

<pre><code class="r">summary(mtcars)
</code></pre>

<pre><code>##       mpg             cyl             disp             hp       
##  Min.   :10.40   Min.   :4.000   Min.   : 71.1   Min.   : 52.0  
##  1st Qu.:15.43   1st Qu.:4.000   1st Qu.:120.8   1st Qu.: 96.5  
##  Median :19.20   Median :6.000   Median :196.3   Median :123.0  
##  Mean   :20.09   Mean   :6.188   Mean   :230.7   Mean   :146.7  
##  3rd Qu.:22.80   3rd Qu.:8.000   3rd Qu.:326.0   3rd Qu.:180.0  
##  Max.   :33.90   Max.   :8.000   Max.   :472.0   Max.   :335.0  
##       drat             wt             qsec             vs        
##  Min.   :2.760   Min.   :1.513   Min.   :14.50   Min.   :0.0000  
##  1st Qu.:3.080   1st Qu.:2.581   1st Qu.:16.89   1st Qu.:0.0000  
##  Median :3.695   Median :3.325   Median :17.71   Median :0.0000  
##  Mean   :3.597   Mean   :3.217   Mean   :17.85   Mean   :0.4375  
##  3rd Qu.:3.920   3rd Qu.:3.610   3rd Qu.:18.90   3rd Qu.:1.0000  
##  Max.   :4.930   Max.   :5.424   Max.   :22.90   Max.   :1.0000  
##        am              gear            carb      
##  Min.   :0.0000   Min.   :3.000   Min.   :1.000  
##  1st Qu.:0.0000   1st Qu.:3.000   1st Qu.:2.000  
##  Median :0.0000   Median :4.000   Median :2.000  
##  Mean   :0.4062   Mean   :3.688   Mean   :2.812  
##  3rd Qu.:1.0000   3rd Qu.:4.000   3rd Qu.:4.000  
##  Max.   :1.0000   Max.   :5.000   Max.   :8.000
</code></pre>

  </article>
  <!-- Presenter Notes -->
  <aside class="note" id="">
    <section>
      <p>word wrapping</p>

    </section>
  </aside>
</slide>

<slide class="" id="slide-20" style="background:;">
  <hgroup>
    <h2>Data frames</h2>
  </hgroup>
  <article data-timings="">
    <p>Quick review of terms form the summary:</p>

<ul>
<li>1st Qu. = the first quantile- means 25% observations are below this<br></li>
<li>3rd Qu. = the third quantile - means 75% observations are below this<br></li>
<li>Median = The middle point. Half the numbers are above this value<br></li>
<li>Mean = average<br></li>
</ul>

  </article>
  <!-- Presenter Notes -->
  <aside class="note" id="">
    <section>
      <p>obvious min and max  </p>

<p>2nd most important thing I have learned.  R is written assuming you are a fluent statistician. (I am not so there is a lot of learning)</p>

    </section>
  </aside>
</slide>

<slide class="" id="slide-21" style="background:;">
  <hgroup>
    <h2>Data frames</h2>
  </hgroup>
  <article data-timings="">
    <p>Let&#39;s confirm the mean of the miles per gallon column (20.09). To get the just the mpg column we use the $</p>

<pre><code class="r"> mtcars$mpg
</code></pre>

<pre><code>##  [1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 17.8 16.4 17.3 15.2
## [15] 10.4 10.4 14.7 32.4 30.4 33.9 21.5 15.5 15.2 13.3 19.2 27.3 26.0 30.4
## [29] 15.8 19.7 15.0 21.4
</code></pre>

<p>then we can sum the column and get its length</p>

<pre><code class="r">sumMPG &lt;- sum(mtcars$mpg)
lengthMPG &lt;- length(mtcars$mpg)

sumMPG/lengthMPG
</code></pre>

<pre><code>## [1] 20.09062
</code></pre>

  </article>
  <!-- Presenter Notes -->
  <aside class="note" id="">
    <section>
      <p>point our the items numbers in the row wrapping [15], 10.4 is the 15th element</p>

    </section>
  </aside>
</slide>

<slide class="" id="slide-22" style="background:;">
  <hgroup>
    <h2>Data frames</h2>
  </hgroup>
  <article data-timings="">
    <pre><code class="r">round(sumMPG/lengthMPG, 2)
</code></pre>

<pre><code>## [1] 20.09
</code></pre>

<p>Perfect!  That matches the summary value of 20.09</p>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-23" style="background:;">
  <hgroup>
    <h2>Packages</h2>
  </hgroup>
  <article data-timings="">
    <ul>
<li>Packages extend the functionality of R.<br></li>
</ul>

<ul class = "build incremental">
<li><p>They can be equated to libraries in .Net</p></li>
<li><p>There are currently packages available on the cran 6,587</p></li>
<li><p>first time you access a package you need to install it: install.packages(&quot;packageName&quot;)</p></li>
<li><p>load the package into memory when you need to use it: library(packageName)  </p></li>
<li><p>Packages may ned to be updated as R upgrades</p></li>
</ul>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-24" style="background:;">
  <hgroup>
    <h2>NA</h2>
  </hgroup>
  <article data-timings="">
    <ul>
<li>When a value in a column is blank.</li>
<li>We can equate them to null values.</li>
<li>Us the function is.na(vector) to find the na&#39;s</li>
<li>is.na returns a Boolean vector of true and false for if the values is na or not</li>
<li>can use sum to get a count of na&#39;s because true = 1 and false = 0</li>
</ul>

<pre><code class="r">x&lt;- c(5, NA, 6, 10, 11)

is.na(x)
</code></pre>

<pre><code>## [1] FALSE  TRUE FALSE FALSE FALSE
</code></pre>

<pre><code class="r">sum(is.na(x))
</code></pre>

<pre><code>## [1] 1
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-25" style="background:;">
  <hgroup>
    <h2>NA</h2>
  </hgroup>
  <article data-timings="">
    <ul>
<li>some function have trouble with na&#39;s so you must tell them what to do with the Na&#39;s</li>
</ul>

<pre><code class="r">x&lt;- c(5, NA, 6, 10, 11)

mean(x)
</code></pre>

<pre><code>## [1] NA
</code></pre>

<pre><code class="r">mean(x, na.rm = TRUE)
</code></pre>

<pre><code>## [1] 8
</code></pre>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-26" style="background:;">
  <hgroup>
    <h2>A real Data set</h2>
  </hgroup>
  <article data-timings="">
    <p>Let&#39;s take a look at the stack overflow developer survey results from the 2015 
<a href="http://stackoverflow.com/research/developer-survey-2015">Stack overflow Developer Survey</a></p>

<p>Demo of using the Console</p>

  </article>
  <!-- Presenter Notes -->
  <aside class="note" id="">
    <section>
      <p>show: 1. set the working directory<br>
  point out: escape back slashes with double slashes like in c# or use the /<br>
2. read the data from the file    3. show the environment variables<br>
4. show the quick text with tab   5. factors<br>
7. packages                       8. help                 9. ...parameter<br>
10. optional parameters  </p>

    </section>
  </aside>
</slide>

<slide class="" id="slide-27" style="background:;">
  <hgroup>
    <h2>Reusable scripts</h2>
  </hgroup>
  <article data-timings="">
    <p>Now let&#39;s say I am interested in what countries the over 60 crowd are in.</p>

<p>Demo the reusable script functions.</p>

  </article>
  <!-- Presenter Notes -->
  <aside class="note" id="">
    <section>
      <p>Point out:
1. comments<br>
2, in a rerun script use function require<br>
3, method returns<br>
4, looping<br>
5. sourcing the script<br>
6. functions are treated like any other object  </p>

    </section>
  </aside>
</slide>

<slide class="" id="slide-28" style="background:;">
  <hgroup>
    <h2>lapply, sapply, tapply</h2>
  </hgroup>
  <article data-timings="">
    <p>looping is great, but R is an interactive language, multi-line loops in the console would be hard, what&#39;s a statistician to do?</p>

<p>To the rescue... the applies!</p>

<ul>
<li>lapply(): Loop over a list and evaluate a function on each element<br></li>
<li>sapply(): Same as lapply but try to simplify the result<br></li>
<li>apply(): Apply a function over the margins of an array<br></li>
<li>tapply(): Apply a function over subsets of a vector<br></li>
<li>mapply(): Multivariate version of lapply<br></li>
</ul>

  </article>
  <!-- Presenter Notes -->
  <aside class="note" id="">
    <section>
      <p>sapply returns a vector, lapply returns a list<br>
demo</p>

    </section>
  </aside>
</slide>

<slide class="" id="slide-29" style="background:;">
  <hgroup>
    <h2>Scoping and free variables in R</h2>
  </hgroup>
  <article data-timings="">
    <p>Consider the function:</p>

<pre><code class="R">f &lt;- function(x, y) {
  x + y - z
}
</code></pre>

<p>This function has 2 formal arguments x and y. In the body of the function there is another symbol z. In this case z is called a <code>free variable</code>. The scoping rules of a language determine how values are assigned to free variables. <code>R uses lexical scoping.</code> </p>

<p>Free variables are not formal arguments and are not local variables. The values of free variables are searched for in the environment in which the function was defined.</p>

  </article>
  <!-- Presenter Notes -->
  <aside class="note" id="">
    <section>
      <p>demo</p>

    </section>
  </aside>
</slide>

<slide class="" id="slide-30" style="background:;">
  <hgroup>
    <h2>Scoping and free variables in R</h2>
  </hgroup>
  <article data-timings="">
    <p>When R tries to bind a value to a symbol, it searches through a series of <code>environments</code> to find the appropriate value. When you are working on the command line and need to retrieve the value of an R object, the order is roughly</p>

<ol>
<li>Search the global environment for a symbol name matching the one requested.<br></li>
<li>Search the namespaces of each of the packages on the search list<br></li>
</ol>

<p>The search list can be found by using the <code>search</code> function.</p>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-31" style="background:;">
  <hgroup>
    <h2>Summary</h2>
  </hgroup>
  <article data-timings="">
    <p>&quot;As you might be aware, R language is an open-source language for programmers, and the language is the product of collaborative evolution from a combination of brilliant minds too numerous to count. Maybe the best result of this is that R Language compilers have been designed keeping a newbie programmer in mind, which makes it an easy language to adapt. However, numerous minds bring numerous differences as well...&quot;</p>

<p>-<a href="https://blog.udemy.com/r-tutorial">Laran Joseph</a></p>

  </article>
  <!-- Presenter Notes -->
  <aside class="note" id="">
    <section>
      <p>up for the challenge</p>

    </section>
  </aside>
</slide>

<slide class="" id="slide-32" style="background:;">
  <hgroup>
    <h2>Want to get started?</h2>
  </hgroup>
  <article data-timings="">
    <ol>
<li><a href="http://cran.r-project.org/">Install R binaries from the CRAN: http://cran.r-project.org</a></li>
<li><a href="http://www.rstudio.com/">Install RStudio</a></li>
<li> Start learning more:<br>

<ul>
<li><a href="http://swirlstats.com/">Learn R in R: swirl</a><br></li>
<li><a href="http://www.rstudio.com/resources/training/online-learning/">http://www.rstudio.com/resources/training/online-learning/</a><br></li>
<li><a href="http://tryr.codeschool.com/">http://tryr.codeschool.com/</a><br></li>
<li><a href="https://www.coursera.org/specialization/jhudatascience/1">Coursera Data Science Specialization</a></li>
</ul></li>
</ol>

  </article>
  <!-- Presenter Notes -->
</slide>

<slide class="" id="slide-33" style="background:;">
  <hgroup>
    <h2>Questions?</h2>
  </hgroup>
  <article data-timings="">
    <p>Feel free to contact me and I will help if I can!  </p>

<p>email me: <a href="mailto:eagroom@yahoo.com">eagroom@yahoo.com</a><br>
find this presentation on github at: <a href="https://github.com/eagroom/IntroToRPresentation">https://github.com/eagroom/IntroToRPresentation</a>  </p>

  </article>
  <!-- Presenter Notes -->
</slide>

    <slide class="backdrop"></slide>
  </slides>
  <div class="pagination pagination-small" id='io2012-ptoc' style="display:none;">
    <ul>
      <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=1 title='About me'>
         1
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=2 title='Why this is important'>
         2
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=3 title='Why Cont.'>
         3
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=4 title='What is R'>
         4
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=5 title='What is R Cont.'>
         5
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=6 title='The Tools'>
         6
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=7 title='Variable assignment'>
         7
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=8 title='Two more ways to assign variables'>
         8
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=9 title='Auto print'>
         9
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=10 title='Vectors'>
         10
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=11 title='Vectors cont.'>
         11
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=12 title='Vectors'>
         12
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=13 title='Vector Math'>
         13
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=14 title='Vector Math'>
         14
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=15 title='Data frames - The most useful object'>
         15
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=16 title='Data frames'>
         16
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=17 title='Data frames'>
         17
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=18 title='Data frames'>
         18
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=19 title='Data frames'>
         19
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=20 title='Data frames'>
         20
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=21 title='Data frames'>
         21
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=22 title='Data frames'>
         22
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=23 title='Packages'>
         23
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=24 title='NA'>
         24
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=25 title='NA'>
         25
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=26 title='A real Data set'>
         26
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=27 title='Reusable scripts'>
         27
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=28 title='lapply, sapply, tapply'>
         28
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=29 title='Scoping and free variables in R'>
         29
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=30 title='Scoping and free variables in R'>
         30
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=31 title='Summary'>
         31
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=32 title='Want to get started?'>
         32
      </a>
    </li>
    <li>
      <a href="#" target="_self" rel='tooltip' 
        data-slide=33 title='Questions?'>
         33
      </a>
    </li>
  </ul>
  </div>  <!--[if IE]>
    <script 
      src="http://ajax.googleapis.com/ajax/libs/chrome-frame/1/CFInstall.min.js">  
    </script>
    <script>CFInstall.check({mode: 'overlay'});</script>
  <![endif]-->
</body>
  <!-- Load Javascripts for Widgets -->
  
  <!-- LOAD HIGHLIGHTER JS FILES -->
  <script src="libraries/highlighters/highlight.js/highlight.pack.js"></script>
  <script>hljs.initHighlightingOnLoad();</script>
  <!-- DONE LOADING HIGHLIGHTER JS FILES -->
   
  </html>